/** Machine-readable failure codes for HelocInterestPaymentWorkflow. */
export const HELOC_INTEREST_FAILURE_CODES = {
  STRATEGY_NOT_ACTIVE: 'STRATEGY_NOT_ACTIVE',
  INTEREST_CHARGE_TIMEOUT: 'INTEREST_CHARGE_TIMEOUT',
  INTEREST_CHARGE_FAILED: 'INTEREST_CHARGE_FAILED',
  INTEREST_DEBIT_TIMEOUT: 'INTEREST_DEBIT_TIMEOUT',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  INTEREST_AMOUNT_MISMATCH: 'INTEREST_AMOUNT_MISMATCH',
  INTEREST_UNEXPECTED_SOURCE: 'INTEREST_UNEXPECTED_SOURCE',
  DEBIT_FAILED: 'DEBIT_FAILED',
  DEBIT_REVERSED: 'DEBIT_REVERSED',
  RECONCILIATION_FAILED: 'RECONCILIATION_FAILED',
  DUPLICATE_CONFLICT: 'DUPLICATE_CONFLICT',
  STRATEGY_PAUSED: 'STRATEGY_PAUSED',
  STRATEGY_CLOSED: 'STRATEGY_CLOSED',
  UNSAFE_OUTCOME: 'UNSAFE_OUTCOME',
  VALIDATION_FAILURE: 'VALIDATION_FAILURE',
} as const;

export type HelocInterestFailureCode =
  (typeof HELOC_INTEREST_FAILURE_CODES)[keyof typeof HELOC_INTEREST_FAILURE_CODES];
