/** Machine-readable failure / skip codes for MonthlyConversionWorkflow. */
export const MONTHLY_CONVERSION_FAILURE_CODES = {
  STRATEGY_NOT_ACTIVE: 'STRATEGY_NOT_ACTIVE',
  MORTGAGE_PAYMENT_TIMEOUT: 'MORTGAGE_PAYMENT_TIMEOUT',
  PAYMENT_REVERSED: 'PAYMENT_REVERSED',
  HELOC_CREDIT_LAG_TIMEOUT: 'HELOC_CREDIT_LAG_TIMEOUT',
  INSUFFICIENT_CREDIT: 'INSUFFICIENT_CREDIT',
  NO_DRAW_CAPACITY: 'NO_DRAW_CAPACITY',
  AMOUNT_BELOW_MINIMUM: 'AMOUNT_BELOW_MINIMUM',
  MONTHLY_CAP: 'MONTHLY_CAP',
  PLATFORM_CAP: 'PLATFORM_CAP',
  HELOC_DRAW_TIMEOUT: 'HELOC_DRAW_TIMEOUT',
  HELOC_DRAW_FAILED: 'HELOC_DRAW_FAILED',
  TRANSFER_TIMEOUT: 'TRANSFER_TIMEOUT',
  TRANSFER_FAILED: 'TRANSFER_FAILED',
  ORDER_TIMEOUT: 'ORDER_TIMEOUT',
  ORDER_REJECTED: 'ORDER_REJECTED',
  PARTIAL_FILL: 'PARTIAL_FILL',
  RECONCILIATION_FAILED: 'RECONCILIATION_FAILED',
  STRATEGY_PAUSED: 'STRATEGY_PAUSED',
  STRATEGY_CLOSED: 'STRATEGY_CLOSED',
  AMBIGUOUS_UNRESOLVED: 'AMBIGUOUS_UNRESOLVED',
  UNSAFE_OUTCOME: 'UNSAFE_OUTCOME',
  VALIDATION_FAILURE: 'VALIDATION_FAILURE',
} as const;

export type MonthlyConversionFailureCode =
  (typeof MONTHLY_CONVERSION_FAILURE_CODES)[keyof typeof MONTHLY_CONVERSION_FAILURE_CODES];
