export function fixtureCorrelationId(): string {
  return '550e8400-e29b-41d4-a716-446655440000';
}

/** Catalogue of failure modes covered by automated packs (see docs/test-matrix.md). */
export const FAILURE_MODE_CATALOGUE = [
  'settlement.immediate',
  'settlement.one_day',
  'settlement.five_days',
  'settlement.never',
  'settlement.reverse_after_posting',
  'settlement.reverse_after_settlement',
  'heloc.readvance_immediate',
  'heloc.readvance_late',
  'heloc.existing_unused_no_new_credit',
  'heloc.insufficient',
  'heloc.blocked',
  'heloc.delinquent',
  'heloc.draw_rejected',
  'heloc.timeout_before_processing',
  'heloc.timeout_after_success',
  'transfer.pending_days',
  'transfer.rejected',
  'transfer.timeout_after_success',
  'transfer.duplicate',
  'transfer.reversed',
  'brokerage.delayed_deposit',
  'brokerage.deposit_reversed',
  'brokerage.insufficient_cash',
  'brokerage.order_rejected',
  'brokerage.partial_fill',
  'brokerage.order_timeout_after_fill',
  'brokerage.price_move',
  'brokerage.account_restricted',
  'brokerage.symbol_policy_changed',
  'temporal.worker_stop_resume',
  'temporal.activity_retries',
  'temporal.duplicated_signals',
  'temporal.out_of_order_signals',
  'temporal.schedule_skip_overlap',
  'temporal.workflow_replay',
  'temporal.resume_no_duplicate_draw',
  'tenancy.cross_user',
  'tenancy.forged_tenant_body',
  'tenancy.cross_tenant_webhook',
  'tenancy.provider_id_reuse',
  'security.invalid_webhook_signature',
  'security.replayed_webhook',
  'security.redacted_logs',
  'interest.debit_success',
  'interest.nsf',
  'interest.reversed',
  'interest.unexpected_account',
  'interest.duplicate_signal',
  'recon.amount_mismatch',
  'recon.duplicate_provider_ref',
  'recon.missing_fill',
  'recon.ledger_imbalance',
  'recon.rerun_stable',
] as const;

export type FailureModeId = (typeof FAILURE_MODE_CATALOGUE)[number];
